version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: "/android-tests"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      docs-dependencies:
        patterns:
          - "*"
