package com.dylibso.chicory.aot;

import com.dylibso.chicory.runtime.OpcodeImpl;
import com.dylibso.chicory.wasm.types.OpCode;
import java.util.Map;

final class AotEmitterMap {

    public static final Map<OpCode, BytecodeEmitter> EMITTERS =
            AotEmitters.builder()
                    // ====== Misc ======
                    .intrinsic(OpCode.DROP, AotEmitters::DROP)
                    .intrinsic(OpCode.ELEM_DROP, AotEmitters::ELEM_DROP)
                    .intrinsic(OpCode.SELECT, AotEmitters::SELECT)
                    .intrinsic(OpCode.SELECT_T, AotEmitters::SELECT)

                    // ====== Control Flow ======
                    .intrinsic(OpCode.CALL, AotEmitters::CALL)
                    .intrinsic(OpCode.CALL_INDIRECT, AotEmitters::CALL_INDIRECT)

                    // ====== References ======
                    .intrinsic(OpCode.REF_FUNC, AotEmitters::REF_FUNC)
                    .intrinsic(OpCode.REF_NULL, AotEmitters::REF_NULL)
                    .intrinsic(OpCode.REF_IS_NULL, AotEmitters::REF_IS_NULL)

                    // ====== Locals & Globals ======
                    .intrinsic(OpCode.LOCAL_GET, AotEmitters::LOCAL_GET)
                    .intrinsic(OpCode.LOCAL_SET, AotEmitters::LOCAL_SET)
                    .intrinsic(OpCode.LOCAL_TEE, AotEmitters::LOCAL_TEE)
                    .intrinsic(OpCode.GLOBAL_GET, AotEmitters::GLOBAL_GET)
                    .intrinsic(OpCode.GLOBAL_SET, AotEmitters::GLOBAL_SET)

                    // ====== Tables ======
                    .intrinsic(OpCode.TABLE_GET, AotEmitters::TABLE_GET)
                    .intrinsic(OpCode.TABLE_SET, AotEmitters::TABLE_SET)
                    .intrinsic(OpCode.TABLE_SIZE, AotEmitters::TABLE_SIZE)
                    .intrinsic(OpCode.TABLE_GROW, AotEmitters::TABLE_GROW)
                    .intrinsic(OpCode.TABLE_FILL, AotEmitters::TABLE_FILL)
                    .intrinsic(OpCode.TABLE_COPY, AotEmitters::TABLE_COPY)
                    .intrinsic(OpCode.TABLE_INIT, AotEmitters::TABLE_INIT)

                    // ====== Memory ======
                    .intrinsic(OpCode.MEMORY_INIT, AotEmitters::MEMORY_INIT)
                    .intrinsic(OpCode.MEMORY_COPY, AotEmitters::MEMORY_COPY)
                    .intrinsic(OpCode.MEMORY_FILL, AotEmitters::MEMORY_FILL)
                    .intrinsic(OpCode.MEMORY_GROW, AotEmitters::MEMORY_GROW)
                    .intrinsic(OpCode.MEMORY_SIZE, AotEmitters::MEMORY_SIZE)
                    .intrinsic(OpCode.DATA_DROP, AotEmitters::DATA_DROP)

                    // ====== Load & Store ======
                    .intrinsic(OpCode.I32_LOAD, AotEmitters::I32_LOAD)
                    .intrinsic(OpCode.I32_LOAD8_S, AotEmitters::I32_LOAD8_S)
                    .intrinsic(OpCode.I32_LOAD8_U, AotEmitters::I32_LOAD8_U)
                    .intrinsic(OpCode.I32_LOAD16_S, AotEmitters::I32_LOAD16_S)
                    .intrinsic(OpCode.I32_LOAD16_U, AotEmitters::I32_LOAD16_U)
                    .intrinsic(OpCode.I64_LOAD, AotEmitters::I64_LOAD)
                    .intrinsic(OpCode.I64_LOAD8_S, AotEmitters::I64_LOAD8_S)
                    .intrinsic(OpCode.I64_LOAD8_U, AotEmitters::I64_LOAD8_U)
                    .intrinsic(OpCode.I64_LOAD16_S, AotEmitters::I64_LOAD16_S)
                    .intrinsic(OpCode.I64_LOAD16_U, AotEmitters::I64_LOAD16_U)
                    .intrinsic(OpCode.I64_LOAD32_S, AotEmitters::I64_LOAD32_S)
                    .intrinsic(OpCode.I64_LOAD32_U, AotEmitters::I64_LOAD32_U)
                    .intrinsic(OpCode.F32_LOAD, AotEmitters::F32_LOAD)
                    .intrinsic(OpCode.F64_LOAD, AotEmitters::F64_LOAD)
                    .intrinsic(OpCode.I32_STORE, AotEmitters::I32_STORE)
                    .intrinsic(OpCode.I32_STORE8, AotEmitters::I32_STORE8)
                    .intrinsic(OpCode.I32_STORE16, AotEmitters::I32_STORE16)
                    .intrinsic(OpCode.I64_STORE, AotEmitters::I64_STORE)
                    .intrinsic(OpCode.I64_STORE8, AotEmitters::I64_STORE8)
                    .intrinsic(OpCode.I64_STORE16, AotEmitters::I64_STORE16)
                    .intrinsic(OpCode.I64_STORE32, AotEmitters::I64_STORE32)
                    .intrinsic(OpCode.F32_STORE, AotEmitters::F32_STORE)
                    .intrinsic(OpCode.F64_STORE, AotEmitters::F64_STORE)

                    // ====== I32 ======
                    .intrinsic(OpCode.I32_ADD, AotEmitters::I32_ADD)
                    .intrinsic(OpCode.I32_AND, AotEmitters::I32_AND)
                    .shared(OpCode.I32_CLZ, OpcodeImpl.class)
                    .intrinsic(OpCode.I32_CONST, AotEmitters::I32_CONST)
                    .shared(OpCode.I32_CTZ, OpcodeImpl.class)
                    .shared(OpCode.I32_DIV_S, OpcodeImpl.class)
                    .shared(OpCode.I32_DIV_U, OpcodeImpl.class)
                    .shared(OpCode.I32_EQ, OpcodeImpl.class)
                    .shared(OpCode.I32_EQZ, OpcodeImpl.class)
                    .shared(OpCode.I32_EXTEND_8_S, OpcodeImpl.class)
                    .shared(OpCode.I32_EXTEND_16_S, OpcodeImpl.class)
                    .shared(OpCode.I32_GE_S, OpcodeImpl.class)
                    .shared(OpCode.I32_GE_U, OpcodeImpl.class)
                    .shared(OpCode.I32_GT_S, OpcodeImpl.class)
                    .shared(OpCode.I32_GT_U, OpcodeImpl.class)
                    .shared(OpCode.I32_LE_S, OpcodeImpl.class)
                    .shared(OpCode.I32_LE_U, OpcodeImpl.class)
                    .shared(OpCode.I32_LT_S, OpcodeImpl.class)
                    .shared(OpCode.I32_LT_U, OpcodeImpl.class)
                    .intrinsic(OpCode.I32_MUL, AotEmitters::I32_MUL)
                    .shared(OpCode.I32_NE, OpcodeImpl.class)
                    .intrinsic(OpCode.I32_OR, AotEmitters::I32_OR)
                    .shared(OpCode.I32_POPCNT, OpcodeImpl.class)
                    .shared(OpCode.I32_REINTERPRET_F32, OpcodeImpl.class)
                    .shared(OpCode.I32_REM_S, OpcodeImpl.class)
                    .shared(OpCode.I32_REM_U, OpcodeImpl.class)
                    .shared(OpCode.I32_ROTL, OpcodeImpl.class)
                    .shared(OpCode.I32_ROTR, OpcodeImpl.class)
                    .intrinsic(OpCode.I32_SHL, AotEmitters::I32_SHL)
                    .intrinsic(OpCode.I32_SHR_S, AotEmitters::I32_SHR_S)
                    .intrinsic(OpCode.I32_SHR_U, AotEmitters::I32_SHR_U)
                    .intrinsic(OpCode.I32_SUB, AotEmitters::I32_SUB)
                    .shared(OpCode.I32_TRUNC_F32_S, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_F32_U, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_F64_S, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_F64_U, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_SAT_F32_S, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_SAT_F32_U, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_SAT_F64_S, OpcodeImpl.class)
                    .shared(OpCode.I32_TRUNC_SAT_F64_U, OpcodeImpl.class)
                    .intrinsic(OpCode.I32_WRAP_I64, AotEmitters::I32_WRAP_I64)
                    .intrinsic(OpCode.I32_XOR, AotEmitters::I32_XOR)

                    // ====== I64 ======
                    .intrinsic(OpCode.I64_ADD, AotEmitters::I64_ADD)
                    .intrinsic(OpCode.I64_AND, AotEmitters::I64_AND)
                    .shared(OpCode.I64_CLZ, OpcodeImpl.class)
                    .intrinsic(OpCode.I64_CONST, AotEmitters::I64_CONST)
                    .shared(OpCode.I64_CTZ, OpcodeImpl.class)
                    .shared(OpCode.I64_DIV_S, OpcodeImpl.class)
                    .shared(OpCode.I64_DIV_U, OpcodeImpl.class)
                    .shared(OpCode.I64_EQ, OpcodeImpl.class)
                    .shared(OpCode.I64_EQZ, OpcodeImpl.class)
                    .shared(OpCode.I64_EXTEND_8_S, OpcodeImpl.class)
                    .shared(OpCode.I64_EXTEND_16_S, OpcodeImpl.class)
                    .shared(OpCode.I64_EXTEND_32_S, OpcodeImpl.class)
                    .intrinsic(OpCode.I64_EXTEND_I32_S, AotEmitters::I64_EXTEND_I32_S)
                    .shared(OpCode.I64_EXTEND_I32_U, OpcodeImpl.class)
                    .shared(OpCode.I64_GE_S, OpcodeImpl.class)
                    .shared(OpCode.I64_GE_U, OpcodeImpl.class)
                    .shared(OpCode.I64_GT_S, OpcodeImpl.class)
                    .shared(OpCode.I64_GT_U, OpcodeImpl.class)
                    .shared(OpCode.I64_LE_S, OpcodeImpl.class)
                    .shared(OpCode.I64_LE_U, OpcodeImpl.class)
                    .shared(OpCode.I64_LT_S, OpcodeImpl.class)
                    .shared(OpCode.I64_LT_U, OpcodeImpl.class)
                    .intrinsic(OpCode.I64_MUL, AotEmitters::I64_MUL)
                    .shared(OpCode.I64_NE, OpcodeImpl.class)
                    .intrinsic(OpCode.I64_OR, AotEmitters::I64_OR)
                    .shared(OpCode.I64_POPCNT, OpcodeImpl.class)
                    .shared(OpCode.I64_REM_S, OpcodeImpl.class)
                    .shared(OpCode.I64_REM_U, OpcodeImpl.class)
                    .shared(OpCode.I64_ROTL, OpcodeImpl.class)
                    .shared(OpCode.I64_ROTR, OpcodeImpl.class)
                    .intrinsic(OpCode.I64_SHL, AotEmitters::I64_SHL)
                    .intrinsic(OpCode.I64_SHR_S, AotEmitters::I64_SHR_S)
                    .intrinsic(OpCode.I64_SHR_U, AotEmitters::I64_SHR_U)
                    .intrinsic(OpCode.I64_SUB, AotEmitters::I64_SUB)
                    .shared(OpCode.I64_REINTERPRET_F64, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_F32_S, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_F32_U, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_F64_S, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_F64_U, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_SAT_F32_S, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_SAT_F32_U, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_SAT_F64_S, OpcodeImpl.class)
                    .shared(OpCode.I64_TRUNC_SAT_F64_U, OpcodeImpl.class)
                    .intrinsic(OpCode.I64_XOR, AotEmitters::I64_XOR)

                    // ====== F32 ======
                    .shared(OpCode.F32_ABS, OpcodeImpl.class)
                    .intrinsic(OpCode.F32_ADD, AotEmitters::F32_ADD)
                    .shared(OpCode.F32_CEIL, OpcodeImpl.class)
                    .intrinsic(OpCode.F32_CONST, AotEmitters::F32_CONST)
                    .shared(OpCode.F32_CONVERT_I32_S, OpcodeImpl.class)
                    .shared(OpCode.F32_CONVERT_I32_U, OpcodeImpl.class)
                    .shared(OpCode.F32_CONVERT_I64_S, OpcodeImpl.class)
                    .shared(OpCode.F32_CONVERT_I64_U, OpcodeImpl.class)
                    .shared(OpCode.F32_COPYSIGN, OpcodeImpl.class)
                    .intrinsic(OpCode.F32_DEMOTE_F64, AotEmitters::F32_DEMOTE_F64)
                    .intrinsic(OpCode.F32_DIV, AotEmitters::F32_DIV)
                    .shared(OpCode.F32_EQ, OpcodeImpl.class)
                    .shared(OpCode.F32_FLOOR, OpcodeImpl.class)
                    .shared(OpCode.F32_GE, OpcodeImpl.class)
                    .shared(OpCode.F32_GT, OpcodeImpl.class)
                    .shared(OpCode.F32_LE, OpcodeImpl.class)
                    .shared(OpCode.F32_LT, OpcodeImpl.class)
                    .shared(OpCode.F32_MAX, OpcodeImpl.class)
                    .shared(OpCode.F32_MIN, OpcodeImpl.class)
                    .intrinsic(OpCode.F32_MUL, AotEmitters::F32_MUL)
                    .shared(OpCode.F32_NE, OpcodeImpl.class)
                    .intrinsic(OpCode.F32_NEG, AotEmitters::F32_NEG)
                    .shared(OpCode.F32_NEAREST, OpcodeImpl.class)
                    .shared(OpCode.F32_REINTERPRET_I32, OpcodeImpl.class)
                    .shared(OpCode.F32_SQRT, OpcodeImpl.class)
                    .intrinsic(OpCode.F32_SUB, AotEmitters::F32_SUB)
                    .shared(OpCode.F32_TRUNC, OpcodeImpl.class)

                    // ====== F64 ======
                    .shared(OpCode.F64_ABS, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_ADD, AotEmitters::F64_ADD)
                    .shared(OpCode.F64_CEIL, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_CONST, AotEmitters::F64_CONST)
                    .shared(OpCode.F64_CONVERT_I32_S, OpcodeImpl.class)
                    .shared(OpCode.F64_CONVERT_I32_U, OpcodeImpl.class)
                    .shared(OpCode.F64_CONVERT_I64_S, OpcodeImpl.class)
                    .shared(OpCode.F64_CONVERT_I64_U, OpcodeImpl.class)
                    .shared(OpCode.F64_COPYSIGN, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_DIV, AotEmitters::F64_DIV)
                    .shared(OpCode.F64_EQ, OpcodeImpl.class)
                    .shared(OpCode.F64_FLOOR, OpcodeImpl.class)
                    .shared(OpCode.F64_GE, OpcodeImpl.class)
                    .shared(OpCode.F64_GT, OpcodeImpl.class)
                    .shared(OpCode.F64_LE, OpcodeImpl.class)
                    .shared(OpCode.F64_LT, OpcodeImpl.class)
                    .shared(OpCode.F64_MAX, OpcodeImpl.class)
                    .shared(OpCode.F64_MIN, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_MUL, AotEmitters::F64_MUL)
                    .shared(OpCode.F64_NE, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_NEG, AotEmitters::F64_NEG)
                    .shared(OpCode.F64_NEAREST, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_PROMOTE_F32, AotEmitters::F64_PROMOTE_F32)
                    .shared(OpCode.F64_REINTERPRET_I64, OpcodeImpl.class)
                    .shared(OpCode.F64_SQRT, OpcodeImpl.class)
                    .intrinsic(OpCode.F64_SUB, AotEmitters::F64_SUB)
                    .shared(OpCode.F64_TRUNC, OpcodeImpl.class)
                    .build();

    private AotEmitterMap() {}
}
