package chicory.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.dylibso.chicory.runtime.Instance;
import com.dylibso.chicory.wasm.types.Value;
import org.junit.jupiter.api.Test;

class PluginOnlyExportsTest {

    @Test
    public void exportsModuleWithPluginOnly() {
        // Use the compiled module generated by the maven plugin
        var instance =
                Instance.builder(AllExportsModule.load())
                        .withMachineFactory(AllExportsModule::create)
                        .build();

        // Use the _ModuleExports generated by the plugin via moduleInterface
        var exports = new AllExportsWrapper_ModuleExports(instance);

        // Assert
        assertEquals(exports.glob1().getValue(), exports.get1());
        assertEquals(exports.glob2().getValue(), exports.get2());
        assertEquals(Value.longToFloat(exports.glob3().getValue()), exports.get3());
        assertEquals(Value.longToDouble(exports.glob4().getValue()), exports.get4());
        assertEquals(exports.glob1().getValue() + 5, exports.get5(5));
        assertEquals(exports.glob2().getValue() + 6, exports.get6(6));
        assertEquals(Value.longToFloat(exports.glob3().getValue()) + 7.0f, exports.get7(7.0f));
        assertEquals(Value.longToDouble(exports.glob4().getValue()) + 8.0d, exports.get8(8.0d));
        assertEquals(46, exports.get9(1, 2L, 3.0f, 4.0d));
        var multiReturn = exports.get10(1, 2L, 3.0f, 4.0d);
        assertEquals(47, multiReturn[0]);
        assertEquals(48, multiReturn[1]);
        assertNotNull(exports.mem());
        assertNotNull(exports.tab());
    }
}
