package com.dylibso.chicory.component.validation;

import com.dylibso.chicory.component.ComponentModel;
import com.dylibso.chicory.component.HostFunctionProvider;
import com.dylibso.chicory.wasm.Parser;
import com.dylibso.chicory.wasm.WasmModule;
import com.example.generated.Color;
import com.example.generated.ExampleComponent;
import com.example.generated.Person;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Phase 12.3: Typed Component Wrapper SDK Test
 *
 * <p>Demonstrates the type-safe SDK approach generated by ComponentWrapperGenerator. Compares:
 * - Untyped: component.callExport("add", 3, 5) returning Object
 * - Typed SDK: component.add(3, 5) returning int directly
 *
 * <p><b>Key Features Tested:</b>
 * <ul>
 *   <li>Primitive type methods with full type safety
 *   <li>POJO input/output with automatic marshalling
 *   <li>Variant types with pattern matching
 *   <li>List types with generic type safety
 *   <li>String handling with charset conversion
 * </ul>
 */
public class TypedComponentWrapperValidator {
    public static void main(String[] mainArgs) throws Exception {
        System.out.println("=== Phase 12.3: Typed Component Wrapper SDK ===\n");

        // Paths to WIT and WASM files
        String basePath = "example/";
        String witSource = Files.readString(Paths.get(basePath + "example.wit"));
        byte[] wasmBytes = Files.readAllBytes(Paths.get(basePath + "example.wasm"));

        System.out.println("[OK] Loaded WIT file: " + basePath + "example.wit");
        System.out.println(
                "[OK] Loaded WASM file: "
                        + basePath
                        + "example.wasm ("
                        + wasmBytes.length
                        + " bytes)\n");

        try {
            // Force load generated classes to register with PojoRegistry
            Class.forName("com.example.generated.Person");
            Class.forName("com.example.generated.UserStatus");
            Class.forName("com.example.generated.OperationResult");
            Class.forName("com.example.generated.Color");
            // Parse WASM bytes
            System.out.println("Parsing WASM module...");
            WasmModule wasmModule = Parser.parse(wasmBytes);
            System.out.println("[OK] WASM module parsed\n");

            // Setup host functions
            HostFunctionProvider hostFunctions = new HostFunctionProvider();
            hostFunctions.register("host-log", hostArgs -> null);
            hostFunctions.register("host-get-input", hostArgs -> "test input");
            hostFunctions.register(
                    "host-log",
                    hostArgs -> {
                        String msg = hostArgs.length > 0 ? (String) hostArgs[0] : "null";
                        System.out.println("  [✅ HOST] host-log(\"" + msg + "\")");
                        return null;
                    });

            hostFunctions.register(
                    "host-get-input",
                    hostArgs -> {
                        System.out.println("  [✅ HOST] host-get-input()");
                        return "hello-from-host";
                    });

            // Load component
            System.out.println("Loading ComponentModel...");
            ComponentModel component =
                    ComponentModel.load(witSource, wasmModule, "$root", hostFunctions);
            System.out.println("[OK] ComponentModel loaded\n");

            // Create typed wrapper (SDK)
            System.out.println("Creating typed SDK wrapper...");
            ExampleComponent sdk = new ExampleComponent(component);
            System.out.println("[OK] Typed wrapper created\n");

            // ===== COMPARISON 1: Primitives =====
            System.out.println("=== COMPARISON 1: Primitive Operations ===\n");

            // Test 1a: Untyped approach (old way)
            System.out.println("Test 1a: add(5, 3) - UNTYPED");
            Object resultUntyped = component.callExport("add", 5, 3);
            int sumUntyped = ((Number) resultUntyped).intValue();
            System.out.println("  Untyped: Object result = component.callExport(\"add\", 5, 3)");
            System.out.println("  Result: " + sumUntyped + " (manual casting required)");
            System.out.println("  ⚠️  Type safety: None - Object requires casting\n");

            // Test 1b: Typed SDK approach (new way)
            System.out.println("Test 1b: add(5, 3) - TYPED SDK");
            int sumTyped = sdk.add(5, 3);
            System.out.println("  Typed: int result = sdk.add(5, 3)");
            System.out.println("  Result: " + sumTyped + " (no casting needed)");
            System.out.println("  ✅ Type safety: Full - return type is int");
            assert sumTyped == sumUntyped : "Results should match";
            System.out.println("  ✅ [PASS] - Typed and untyped give same result\n");

            // Test 2: Multiple typed operations
            System.out.println("Test 2: Multiple operations via typed SDK");
            long mul = sdk.multiply(4L, 7L);
            boolean pos = sdk.isPositive(42);
            System.out.println("  multiply(4, 7) = " + mul);
            System.out.println("  is-positive(42) = " + pos);
            assert mul == 28 : "Expected 28";
            assert pos == true : "Expected true";
            System.out.println("  ✅ [PASS] - Multiple operations working\n");

            // ===== COMPARISON 2: Records (POJOs) =====
            System.out.println("=== COMPARISON 2: Record Types (POJOs) ===\n");

            // Test 3a: Untyped record handling
            System.out.println("Test 3a: create-person - UNTYPED");
            Object resultObj = component.callExport("create-person", "Alice", 30);
            System.out.println(
                    "  Untyped: Object result = component.callExport(\"create-person\", ...)");
            System.out.println("  Result type: " + resultObj.getClass().getSimpleName());
            System.out.println("  Result: " + resultObj);
            System.out.println("  ⚠️  Type safety: None - manual cast to Person needed\n");

            // Test 3b: Typed SDK record handling
            System.out.println("Test 3b: createPerson - TYPED SDK");
            Person personTyped = sdk.createPerson("Bob", 25);
            System.out.println("  Typed: Person result = sdk.createPerson(\"Bob\", 25)");
            System.out.println("  Result type: " + personTyped.getClass().getSimpleName());
            System.out.println("  Result: " + personTyped);
            System.out.println("  ✅ Type safety: Full - return type is Person POJO");
            assert "Bob".equals(personTyped.getName()) : "Expected name=Bob";
            assert personTyped.getAge() == 25 : "Expected age=25";
            System.out.println("  ✅ [PASS] - POJO type safety working\n");

            // Test 4: POJO input to SDK
            System.out.println("Test 4: POJO input via typed SDK");
            Person input = new Person("Charlie", 35, true);
            String description = sdk.describePerson(input);
            System.out.println("  Input POJO: " + input);
            System.out.println(
                    "  SDK method: sdk.describePerson("
                            + input.getName()
                            + ", "
                            + input.getAge()
                            + ", "
                            + input.getActive()
                            + ")");
            System.out.println("  Description: " + description);
            System.out.println("  ✅ [PASS] - POJO inputs via SDK\n");

            // ===== COMPARISON 3: Variants =====
            System.out.println("=== COMPARISON 3: Variant Types ===\n");

            // Test 5a: Untyped variant
            System.out.println("Test 5a: pick-color - UNTYPED");
            Object colorUntyped = component.callExport("pick-color", 0);
            System.out.println(
                    "  Untyped: Object result = component.callExport(\"pick-color\", 0)");
            System.out.println("  Result type: " + colorUntyped.getClass().getSimpleName());
            System.out.println("  ⚠️  Type safety: None - Object requires instanceof checks\n");

            // Test 5b: Typed SDK variant
            System.out.println("Test 5b: pickColor - TYPED SDK");
            Color colorTyped = sdk.pickColor(0);
            System.out.println("  Typed: Color result = sdk.pickColor(0)");
            System.out.println("  Result type: " + colorTyped.getClass().getSimpleName());
            System.out.println("  Result: " + colorTyped);
            System.out.println("  ✅ Type safety: Full - return type is Color sealed class");
            assert colorTyped instanceof Color.Red : "Expected Red variant";
            System.out.println("  ✅ [PASS] - Variant type safety working\n");

            // Test 6: Variant pattern matching
            System.out.println("Test 6: Pattern matching on variant results");
            Color[] colorTests = {sdk.pickColor(0), sdk.pickColor(1), sdk.pickColor(2)};
            String[] colorNames = {"Red", "Green", "Blue"};
            for (int i = 0; i < colorTests.length; i++) {
                Color c = colorTests[i];
                String name;
                if (c instanceof Color.Red) {
                    name = "Red";
                } else if (c instanceof Color.Green) {
                    name = "Green";
                } else if (c instanceof Color.Blue) {
                    name = "Blue";
                } else {
                    name = "Unknown";
                }
                System.out.println("  pickColor(" + i + ") = " + name);
                assert colorNames[i].equals(name) : "Expected " + colorNames[i];
            }
            System.out.println("  ✅ [PASS] - Pattern matching on variant POJOs\n");

            // ===== COMPARISON 4: Complex Lists =====
            System.out.println("=== COMPARISON 4: List Types ===\n");

            // Test 7a & 7b: Typed list handling with SDK
            System.out.println("Test 7a/7b: getNames - TYPED SDK");
            List<Person> peopleList = new ArrayList<>();
            peopleList.add(new Person("Diana", 32, true));
            peopleList.add(new Person("Eve", 28, true));

            List<String> namesTyped = sdk.getNames(peopleList);
            System.out.println("  Result type: " + namesTyped.getClass().getSimpleName());
            System.out.println("  Result: " + namesTyped);
            System.out.println("  ✅ Type safety: Full - List<String> is type-safe\n");

            // ===== FULL WORKFLOW: End-to-End with SDK =====
            System.out.println("=== FULL WORKFLOW: End-to-End Typed SDK Usage ===\n");

            System.out.println("Scenario: Process a group of people and filter high-value ones");
            List<Person> people = new ArrayList<>();
            people.add(new Person("Frank", 29, true));
            people.add(new Person("Grace", 26, false));
            people.add(new Person("Henry", 31, true));

            System.out.println("  Input: 3 people (ages: 29, 26, 31)");
            System.out.println("  Filtering: age >= 28");

            List<Person> filtered = sdk.filterHighValuePeople(people, 28);
            System.out.println("  Output: " + filtered.size() + " people matched");
            System.out.println("  Expected: 2 people (Frank: 29, Henry: 31)");
            assert filtered.size() == 2 : "Expected 2 filtered results";
            System.out.println("  ✅ [PASS] - Complex typed SDK workflow\n");

            // ===== SUMMARY =====
            System.out.println("=== SUMMARY: Typed SDK Benefits ===\n");
            System.out.println("✅ Type-safe method signatures (no Object return types)");
            System.out.println("✅ IDE auto-completion and refactoring support");
            System.out.println("✅ Compile-time type checking (no runtime casting errors)");
            System.out.println("✅ POJO integration (automatic marshalling/unmarshalling)");
            System.out.println("✅ Pattern matching on variant types");
            System.out.println("✅ Readable, intent-clear API\n");

            System.out.println("Comparison Summary:");
            System.out.println("  Old (Untyped):    component.callExport(\"add\", 3, 5)");
            System.out.println("  New (Typed SDK):  sdk.add(3, 5)");
            System.out.println(
                    "\n  Old (Untyped):    (Person) component.callExport(\"get-person\")");
            System.out.println("  New (Typed SDK):  sdk.getPerson()");
            System.out.println("\nAll 7 typed SDK tests PASSED ✅\n");

        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    private static Map<String, Object> createPersonMap(String name, int age, boolean active) {
        Map<String, Object> person = new HashMap<>();
        person.put("name", name);
        person.put("age", age);
        person.put("active", active);
        return person;
    }
}
